### ISSUE TITLE
sqlite database sometimes locks up when spawning villages.

### ISSUE THREAD

**Issue by crispiebacon** [VoxelForge/VoxelForge#52] opened 2024-07-20 00:34 UTC
Once again since the update the sqlite database sometimes locks up when generating villages.

**Comment by DragonWrangler1** [comment] 2024-07-20 00:45
it runs out of memory ? How do you reproduce it ?

**Comment by DragonWrangler1** [comment] 2024-07-20 01:34
Closing since your pr seems to fix it. I think.

**Closed by DragonWrangler1** 2024-07-20 01:34 UTC
Labels: bug, P6: Critical
